from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_integration_device_ownership_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_mfa', models.IntegerField(default=0)),
                ('ca_no_mfa', models.IntegerField(default=0)),
                ('no_ca_mfa', models.IntegerField(default=0)),
                ('no_ca_no_mfa', models.IntegerField(default=0)),
                ('total_signins', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sign-In Summary',
                'verbose_name_plural': 'Sign-In Summaries',
            },
        ),
        migrations.RunSQL(
            sql=["""
                CREATE TABLE IF NOT EXISTS main_signinsummary (
                    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    ca_mfa integer NOT NULL DEFAULT 0,
                    ca_no_mfa integer NOT NULL DEFAULT 0,
                    no_ca_mfa integer NOT NULL DEFAULT 0,
                    no_ca_no_mfa integer NOT NULL DEFAULT 0,
                    total_signins integer NOT NULL DEFAULT 0,
                    synced_at timestamp with time zone NOT NULL DEFAULT now()
                );
            """],
            reverse_sql=["DROP TABLE IF EXISTS main_signinsummary;"],
            state_operations=[],
        ),
    ]
