# Generated by Django 6.0.3 on 2026-04-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_active_directory_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={},
        ),
        migrations.AlterField(
            model_name='conditionalaccesspolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='control',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='controlframework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='client_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='client_secret',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant_domain',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsecurityconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
